diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # http://127.0.0.1:8000/diary/
    path('add/', views.AddView.as_view(), name='add'), # http://127.0.0.1:8000/diary/add
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'), # http://127.0.0.1:8000/diary/update
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'), # http://127.0.0.1:8000/diary/delete
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'), # http://127.0.0.1:8000/diary/detail
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

diary/models.py
from django.db import models
from django.utils import timezone


class Day(models.Model):
    title = models.CharField('タイトル',max_length = 100)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default = timezone.now)
    
    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from .models import Day

class DayCreateFrom(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'

diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateFrom
from .models import Day

class IndexView(generic.ListView):
    model = Day
    paginate_by = 2

class AddView(LoginRequiredMixin, generic.CreateView):
    model = Day
    form_class = DayCreateFrom
    # 文字列のURLを返却
    success_url = reverse_lazy('diary:index') # http://127.0.0.1:8000/diary/

class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Day
    form_class = DayCreateFrom
    success_url = reverse_lazy('diary:index') # http://127.0.0.1:8000/diary/

class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Day
    success_url = reverse_lazy('diary:index') # http://127.0.0.1:8000/diary/

class DetailView(generic.DetailView):
    model = Day

diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block extracss %}{% endblock %}
    <title>日記アプリケーション</title>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
          <a class="nav-link active" href="{% url 'diary:index'%}">一覧</a>
          {% if user.is_superuser %}
          <a class="nav-link active" href="{% url 'diary:add' %}" target="_blank">追加</a>
          {% endif %}
      </ul>
      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

diary/templates/diary/day_confirm_delete.html
<!doctype html>
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <th>{{ day.title }}</th>
        </tr>
        <tr>
            <th>本文</th>
            <th>{{ day.text }}</th>
        </tr>
        <tr>
            <th>日付</th>
            <th>{{ day.date }}</th>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_detail.html
<!doctype html>
{% extends 'diary/base.html' %}

{% block content %}
<table class="table">
  <tr>
    <th>タイトル</th>
    <th>{{ day.title }}</th>
  </tr>
  <tr>
    <th>本文</th>
    <th>{{ day.text | linebreaksbr }}</th>
  </tr>
  <tr>
    <th>日付</th>
    <th>{{ day.date }}</th>
  </tr>
</table>
{% endblock %}

diary/templates/diary/day_form.html
<!doctype html>
{% extends 'diary/base.html' %}

{% block content %}
<br>
<p>{{ day.title }}</p>
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>{{ form.title.label }}</th>
            <th>{{ form.title }}</th>
        </tr>
        <tr>
            <th>{{ form.text.label }}</th>
            <th>{{ form.text }}</th>
        </tr>
        <tr>
            <th>{{ form.date.label }}</th>
            <th>{{ form.date }}</th>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_list.html
<!doctype html>
{% extends 'diary/base.html' %}

{% block content %}
<br>
<h1>日記一覧</h1>
<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      <th>#</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
    {% for day in day_list %}
      <tr>
        <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
        <td>{{ day.date }}</td>
        <td>
          {% if user.is_superuser %}
          <a href="{% url 'diary:update' day.pk %}" target="_blank">更新</a>
          {% endif %}
        </td>
        <td>
          {% if user.is_superuser %}
          <a href="{% url 'diary:delete' day.pk %}" target="_blank">削除</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>


{% include 'diary/page4.html' %}
{% endblock %}

diary/templates/diary/page1.html
<!doctype html>
<!-- 前へ の部分 -->
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}
 

<!-- 次へ の部分 -->
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

diary/templates/diary/page2.html
<!doctype html>
<!-- 前へ の部分 -->
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}
 
<!-- 数字の部分 -->
{% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
    <span>{{ num }}</span>
  {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}
 
<!-- 次へ の部分 -->
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

diary/templates/diary/page3.html
<!doctype html>
<!-- 前へ の部分 -->
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 数字の部分 -->
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
 
<!-- 次へ の部分 -->
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

diary/templates/diary/page4.html
<!doctype html>
<nav aria-label="Page navigation">
    <ul class="pagination">
   
        {% if page_obj.has_previous %}
          <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% endif %}
      
        {% for link_page in page_obj.paginator.page_range %}
          {% if link_page == page_obj.number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ link_page }}">
                {{ link_page }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ link_page }}">
                {{ link_page }}
              </a>
            </li>
          {% endif %}
        {% endfor %}
      
        {% if page_obj.has_next %}
          <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% endif %}
      
    </ul>
  </nav>
  